# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  comment-output:
    environment: main
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      output1: ${{ steps.step1.outputs.outputKey }}
    steps:
      - id: step1
        name: checkout repo
        uses: actions/checkout@v3
      - id: step2
        name: install nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: latest
      - id: step3
        name: install packages
        run: cd src; npm install;
      - id: step4
        name: run script
        run: cd src/javascript; node index.mjs
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${secrets.CLIENT_SECRET}}
      - id: step5
        name: print
        run: echo "${{steps.step4.outputs.outputKey}}"
      
      

