# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  # add-comment:
  #   environment:
  #     name: main
  #   runs-on: ubuntu-latest
  #   permissions:
  #     issues: write
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v3
  #     - name: install ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.2'
  #         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  #     - name: exec ruby file
  #       run: bundle exec ruby src/generate_jwt.rb
  #     - name: Add comment
  #       uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
  #       with:
  #         token: ${{ secrets.APP_TOKEN }}
  #         issue-number: ${{ github.event.issue.number }}
  #         body: |
  #           This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
  comment-output:
    environment: main
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      output1: ${{ steps.step1.outputs.outputKey }}
    steps:
      - id: step1
        name: checkout repo
        uses: actions/checkout@v3
      - id: step2
        name: install nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: latest
      - id: step3
        name: install packages
        run: cd src; npm install;
      - id: step4
        name: run script
        run: node index.js
      - id: step5
        name: print
        run: echo "${{steps.step1.outputs.outputKey}}""
      
      

